import type { Application } from "@/types/application"
import type { FormSchema } from "@/types/form"

// Моковые данные заявлений
export const mockApplications: Application[] = [
  {
    id: "app-1",
    number: "2023-156",
    title: "Заявление на получение разрешения на строительство",
    status: "approved",
    createdAt: "2023-12-01T10:30:00Z",
    updatedAt: "2023-12-10T14:45:00Z",
    formData: {
      applicantName: "Иванов Иван Иванович",
      applicantEmail: "ivanov@example.com",
      applicantPhone: "+7 (999) 123-45-67",
      objectAddress: "г. Москва, ул. Примерная, д. 123",
      objectType: "residential",
      objectArea: 150,
      hasDocuments: true,
    },
    history: [
      {
        action: "Создание заявления",
        user: "Иванов Иван Иванович",
        timestamp: "2023-12-01T10:30:00Z",
        fromStatus: null,
        toStatus: "draft",
      },
      {
        action: "Отправка на рассмотрение",
        user: "Иванов Иван Иванович",
        timestamp: "2023-12-01T11:15:00Z",
        fromStatus: "draft",
        toStatus: "not_reviewed",
      },
      {
        action: "Принятие в работу",
        user: "Петрова Анна Сергеевна",
        timestamp: "2023-12-02T09:20:00Z",
        fromStatus: "not_reviewed",
        toStatus: "under_review_eo",
      },
      {
        action: "Назначение ответственного",
        user: "Петрова Анна Сергеевна",
        timestamp: "2023-12-02T10:05:00Z",
        fromStatus: "under_review_eo",
        toStatus: "under_review_level_1",
      },
      {
        action: "Отправка на доработку",
        user: "Сидоров Петр Алексеевич",
        timestamp: "2023-12-03T14:30:00Z",
        fromStatus: "under_review_level_1",
        toStatus: "for_revision",
        comment: "Необходимо предоставить дополнительные документы по проекту",
      },
      {
        action: "Отправка заявителю",
        user: "Петрова Анна Сергеевна",
        timestamp: "2023-12-03T15:10:00Z",
        fromStatus: "for_revision",
        toStatus: "revision_applicant",
      },
      {
        action: "Повторная отправка",
        user: "Иванов Иван Иванович",
        timestamp: "2023-12-05T11:45:00Z",
        fromStatus: "revision_applicant",
        toStatus: "under_review_level_1",
      },
      {
        action: "Одобрение",
        user: "Сидоров Петр Алексеевич",
        timestamp: "2023-12-08T10:20:00Z",
        fromStatus: "under_review_level_1",
        toStatus: "approved",
      },
    ],
    comments: [
      {
        id: "comment-1",
        author: "Петрова Анна Сергеевна",
        text: "Заявление принято в работу",
        createdAt: "2023-12-02T09:25:00Z",
      },
      {
        id: "comment-2",
        author: "Сидоров Петр Алексеевич",
        text: "Необходимо предоставить дополнительные документы по проекту: план земельного участка и технические условия подключения к инженерным сетям",
        createdAt: "2023-12-03T14:35:00Z",
      },
      {
        id: "comment-3",
        author: "Иванов Иван Иванович",
        text: "Дополнительные документы предоставлены",
        createdAt: "2023-12-05T11:40:00Z",
      },
      {
        id: "comment-4",
        author: "Сидоров Петр Алексеевич",
        text: "Документы проверены, заявление одобрено",
        createdAt: "2023-12-08T10:15:00Z",
      },
    ],
  },
  {
    id: "app-2",
    number: "2023-157",
    title: "Заявление на получение выписки из реестра",
    status: "under_review_eo",
    createdAt: "2023-12-05T09:15:00Z",
    updatedAt: "2023-12-06T11:30:00Z",
    formData: {
      applicantName: "Смирнова Елена Павловна",
      applicantEmail: "smirnova@example.com",
      applicantPhone: "+7 (999) 987-65-43",
      requestType: "property",
      propertyAddress: "г. Санкт-Петербург, пр. Невский, д. 45, кв. 12",
    },
    history: [
      {
        action: "Создание заявления",
        user: "Смирнова Елена Павловна",
        timestamp: "2023-12-05T09:15:00Z",
        fromStatus: null,
        toStatus: "draft",
      },
      {
        action: "Отправка на рассмотрение",
        user: "Смирнова Елена Павловна",
        timestamp: "2023-12-05T09:20:00Z",
        fromStatus: "draft",
        toStatus: "not_reviewed",
      },
      {
        action: "Принятие в работу",
        user: "Петрова Анна Сергеевна",
        timestamp: "2023-12-06T11:30:00Z",
        fromStatus: "not_reviewed",
        toStatus: "under_review_eo",
      },
    ],
    comments: [
      {
        id: "comment-1",
        author: "Петрова Анна Сергеевна",
        text: "Заявление принято в работу",
        createdAt: "2023-12-06T11:35:00Z",
      },
    ],
  },
  {
    id: "app-3",
    number: "2023-158",
    title: "Заявление на регистрацию права собственности",
    status: "revision_applicant",
    createdAt: "2023-12-03T14:20:00Z",
    updatedAt: "2023-12-07T16:45:00Z",
    formData: {
      applicantName: "Козлов Алексей Дмитриевич",
      applicantEmail: "kozlov@example.com",
      applicantPhone: "+7 (999) 456-78-90",
      propertyType: "apartment",
      propertyAddress: "г. Казань, ул. Центральная, д. 78, кв. 45",
      documentNumber: "78АБ123456",
    },
    history: [
      {
        action: "Создание заявления",
        user: "Козлов Алексей Дмитриевич",
        timestamp: "2023-12-03T14:20:00Z",
        fromStatus: null,
        toStatus: "draft",
      },
      {
        action: "Отправка на рассмотрение",
        user: "Козлов Алексей Дмитриевич",
        timestamp: "2023-12-03T14:30:00Z",
        fromStatus: "draft",
        toStatus: "not_reviewed",
      },
      {
        action: "Принятие в работу",
        user: "Петрова Анна Сергеевна",
        timestamp: "2023-12-04T10:15:00Z",
        fromStatus: "not_reviewed",
        toStatus: "under_review_eo",
      },
      {
        action: "Назначение ответственного",
        user: "Петрова Анна Сергеевна",
        timestamp: "2023-12-04T10:45:00Z",
        fromStatus: "under_review_eo",
        toStatus: "under_review_level_1",
      },
      {
        action: "Отправка на доработку",
        user: "Сидоров Петр Алексеевич",
        timestamp: "2023-12-06T11:20:00Z",
        fromStatus: "under_review_level_1",
        toStatus: "for_revision",
        comment: "Необходимо предоставить оригинал документа о праве собственности",
      },
      {
        action: "Отправка заявителю",
        user: "Петрова Анна Сергеевна",
        timestamp: "2023-12-07T16:45:00Z",
        fromStatus: "for_revision",
        toStatus: "revision_applicant",
      },
    ],
    comments: [
      {
        id: "comment-1",
        author: "Петрова Анна Сергеевна",
        text: "Заявление принято в работу",
        createdAt: "2023-12-04T10:20:00Z",
      },
      {
        id: "comment-2",
        author: "Сидоров Петр Алексеевич",
        text: "Необходимо предоставить оригинал документа о праве собственности. Копия не принимается.",
        createdAt: "2023-12-06T11:25:00Z",
      },
    ],
  },
  {
    id: "app-4",
    number: null,
    title: "Заявление на получение разрешения на перепланировку",
    status: "draft",
    createdAt: "2023-12-08T15:10:00Z",
    updatedAt: "2023-12-08T15:10:00Z",
    formData: {
      applicantName: "Иванов Иван Иванович",
      propertyAddress: "г. Москва, ул. Примерная, д. 123, кв. 45",
    },
    history: [
      {
        action: "Создание заявления",
        user: "Иванов Иван Иванович",
        timestamp: "2023-12-08T15:10:00Z",
        fromStatus: null,
        toStatus: "draft",
      },
    ],
    comments: [],
  },
  {
    id: "app-5",
    number: "2023-159",
    title: "Заявление на получение архивной справки",
    status: "rejected",
    createdAt: "2023-11-20T09:45:00Z",
    updatedAt: "2023-11-28T14:30:00Z",
    formData: {
      applicantName: "Петров Сергей Владимирович",
      applicantEmail: "petrov@example.com",
      applicantPhone: "+7 (999) 111-22-33",
      requestType: "archive",
      requestPeriod: "2010-2015",
      requestDetails: "Информация о владении земельным участком",
    },
    history: [
      {
        action: "Создание заявления",
        user: "Петров Сергей Владимирович",
        timestamp: "2023-11-20T09:45:00Z",
        fromStatus: null,
        toStatus: "draft",
      },
      {
        action: "Отправка на рассмотрение",
        user: "Петров Сергей Владимирович",
        timestamp: "2023-11-20T10:00:00Z",
        fromStatus: "draft",
        toStatus: "not_reviewed",
      },
      {
        action: "Принятие в работу",
        user: "Петрова Анна Сергеевна",
        timestamp: "2023-11-21T09:30:00Z",
        fromStatus: "not_reviewed",
        toStatus: "under_review_eo",
      },
      {
        action: "Назначение ответственного",
        user: "Петрова Анна Сергеевна",
        timestamp: "2023-11-21T10:15:00Z",
        fromStatus: "under_review_eo",
        toStatus: "under_review_level_1",
      },
      {
        action: "Отказ",
        user: "Сидоров Петр Алексеевич",
        timestamp: "2023-11-27T11:45:00Z",
        fromStatus: "under_review_level_1",
        toStatus: "rejected",
        comment: "Запрашиваемая информация отсутствует в архиве",
      },
    ],
    comments: [
      {
        id: "comment-1",
        author: "Петрова Анна Сергеевна",
        text: "Заявление принято в работу",
        createdAt: "2023-11-21T09:35:00Z",
      },
      {
        id: "comment-2",
        author: "Сидоров Петр Алексеевич",
        text: "После проверки архивных данных установлено, что запрашиваемая информация отсутствует в архиве за указанный период",
        createdAt: "2023-11-27T11:50:00Z",
      },
    ],
  },
]

// Моковая схема формы заявления
export const mockFormSchema: FormSchema = {
  sections: [
    {
      title: "Информация о заявителе",
      fields: [
        {
          name: "applicantType",
          label: "Тип заявителя",
          type: "select",
          required: true,
          options: [
            { label: "Физическое лицо", value: "individual" },
            { label: "Юридическое лицо", value: "legal" },
          ],
        },
        {
          name: "applicantName",
          label: "ФИО заявителя",
          type: "text",
          required: true,
          placeholder: "Иванов Иван Иванович",
          dependsOn: {
            field: "applicantType",
            value: "individual",
          },
        },
        {
          name: "companyName",
          label: "Наименование организации",
          type: "text",
          required: true,
          placeholder: "ООО 'Организация'",
          dependsOn: {
            field: "applicantType",
            value: "legal",
          },
        },
        {
          name: "inn",
          label: "ИНН",
          type: "text",
          required: true,
          placeholder: "1234567890",
          dependsOn: {
            field: "applicantType",
            value: "legal",
          },
        },
        {
          name: "applicantEmail",
          label: "Электронная почта",
          type: "text",
          required: true,
          placeholder: "example@mail.ru",
        },
        {
          name: "applicantPhone",
          label: "Номер телефона",
          type: "text",
          required: true,
          placeholder: "+7 (999) 123-45-67",
        },
      ],
    },
    {
      title: "Информация о заявлении",
      fields: [
        {
          name: "requestType",
          label: "Тип заявления",
          type: "select",
          required: true,
          options: [
            { label: "Разрешение на строительство", value: "construction" },
            { label: "Выписка из реестра", value: "registry" },
            { label: "Регистрация права собственности", value: "property" },
            { label: "Разрешение на перепланировку", value: "renovation" },
            { label: "Архивная справка", value: "archive" },
          ],
        },
        {
          name: "objectAddress",
          label: "Адрес объекта",
          type: "text",
          required: true,
          placeholder: "г. Москва, ул. Примерная, д. 123",
          dependsOn: {
            field: "requestType",
            value: "construction",
          },
        },
        {
          name: "objectType",
          label: "Тип объекта",
          type: "select",
          required: true,
          options: [
            { label: "Жилой дом", value: "residential" },
            { label: "Коммерческое здание", value: "commercial" },
            { label: "Промышленный объект", value: "industrial" },
          ],
          dependsOn: {
            field: "requestType",
            value: "construction",
          },
        },
        {
          name: "objectArea",
          label: "Площадь объекта (кв.м)",
          type: "number",
          required: true,
          placeholder: "100",
          dependsOn: {
            field: "requestType",
            value: "construction",
          },
        },
        {
          name: "propertyAddress",
          label: "Адрес недвижимости",
          type: "text",
          required: true,
          placeholder: "г. Москва, ул. Примерная, д. 123, кв. 45",
          dependsOn: {
            field: "requestType",
            value: "property",
          },
        },
        {
          name: "documentNumber",
          label: "Номер документа",
          type: "text",
          required: true,
          placeholder: "78АБ123456",
          dependsOn: {
            field: "requestType",
            value: "property",
          },
        },
        {
          name: "requestPeriod",
          label: "Период запроса",
          type: "text",
          required: true,
          placeholder: "2010-2015",
          dependsOn: {
            field: "requestType",
            value: "archive",
          },
        },
        {
          name: "requestDetails",
          label: "Детали запроса",
          type: "textarea",
          required: true,
          placeholder: "Опишите детали запроса",
          rows: 4,
          fullWidth: true,
          dependsOn: {
            field: "requestType",
            value: "archive",
          },
        },
      ],
    },
    {
      title: "Документы",
      fields: [
        {
          name: "hasDocuments",
          label: "Документы прикреплены",
          type: "checkbox",
          checkboxLabel: "Я подтверждаю, что все необходимые документы прикреплены",
          required: true,
        },
        {
          name: "mainDocument",
          label: "Основной документ",
          type: "file",
          required: true,
        },
        {
          name: "additionalDocuments",
          label: "Дополнительные документы",
          type: "file",
          required: false,
          description: "Можно прикрепить дополнительные документы при необходимости",
        },
        {
          name: "agreement",
          label: "Согласие на обработку персональных данных",
          type: "checkbox",
          checkboxLabel: "Я даю согласие на обработку моих персональных данных",
          required: true,
        },
      ],
    },
  ],
}

